from collections.abc import Sequence
from pathlib import Path

from docx import Document
from docx.shared import Pt
from beetsplug.cd.cd import CD
from beetsplug.document.text_data import TextData


class DocumentBuilder:
    def __init__(self, cds: Sequence[CD]):
        self._cds = cds

    def _get_text(self, cd: CD) -> list[TextData]:
        disc_tracklists = cd.get_tracklist()
        text_data: list[TextData] = []

        for i, tracklist in enumerate(disc_tracklists):
            header = cd.path.name if len(disc_tracklists) == 1 else f"{cd.path.name} (Disc {i+1})"
            text_data.append(TextData(header, bold=True))
            for track in tracklist:
                text_data.append(TextData(track, bold=False))
        return text_data

    def create_document(self, path: Path):
        # Note: Most of this was generated by Claude:
        # https://claude.ai/public/artifacts/24e94a82-d1cb-4a3d-b525-cbae5b59f529
        # I've rewritten most of the code to ensure I understand what's happening,
        # but I honestly don't know enough about docx to know if this is necessarily correct.
        doc = Document()
        section = doc.sections[0]

        sect_pr = section._sectPr
        cols = sect_pr.xpath("./w:cols")[0] if sect_pr.xpath("./w:cols") else None
        
        if cols is None:
            from docx.oxml import parse_xml
            cols_xml = "<w:cols xmlns:w=\"http://schemas.openxmlformats.org/wordprocessingml/2006/main\" w:num=\"2\" w:space=\"720\"/>"
            cols = parse_xml(cols_xml)

            # TODO: Is this real?
            sect_pr.append(cols)
        else:
            # Modify existing cols element
            # TODO: The braces is... weird. Is this expected, or weird formatting?
            cols.set("{http://schemas.openxmlformats.org/wordprocessingml/2006/main}num", "2")
            cols.set("{http://schemas.openxmlformats.org/wordprocessingml/2006/main}space", "720")  # 0.5 inch spacing

        for cd in self._cds:
            text_data = self._get_text(cd)
            for data in text_data:
                paragraph = doc.add_paragraph(data.text)
                for run in paragraph.runs:
                    run.font.size = Pt(11)
                    run.bold = data.bold

        doc.save(str(path))


if __name__ == "__main__":
    from beetsplug.cd.audio.audio_cd import AudioCD
    from beetsplug.dimensional_thread_pool_executor import DimensionalThreadPoolExecutor
    with DimensionalThreadPoolExecutor(1) as executor:
        DocumentBuilder([AudioCD(Path(), [], executor)]).create_document(Path("test-doc.docx"))
